"""WHUMPF API: bulletin proxy plus route analysis. No database.

    flask --app api.app run --debug
"""

from __future__ import annotations

import time

from flask import Flask, abort, jsonify, request, send_from_directory
from flask_cors import CORS

from api.bulletin import get_adapter
from api.features import get_adapter as get_feature_adapter
from api.features import parse_kinds
from pipeline.config import all_aoi_slugs, load_aoi

CACHE_TTL = 30 * 60
_cache: dict[str, tuple[float, dict]] = {}

# Terrain features change on OSM's edit cadence, not a forecast cadence, and
# Overpass is a shared free service -- so this is cached far longer and far
# more aggressively than the bulletin.
FEATURES_CACHE_TTL = 24 * 60 * 60
_features_cache: dict[str, tuple[float, dict]] = {}


def create_app() -> Flask:
    app = Flask(__name__)
    CORS(app)

    @app.get("/api/health")
    def health():
        return jsonify({"ok": True, "aois": all_aoi_slugs()})

    @app.get("/api/aois")
    def aois():
        out = []
        for slug in all_aoi_slugs():
            a = load_aoi(slug)
            out.append({
                "slug": a.slug,
                "name": a.name,
                "country": a.country,
                "hemisphere": a.hemisphere,
                "bbox": a.bbox.as_list(),
                "ion_asset_id": a.elevation.ion_asset_id,
                "bands": {k: list(v) for k, v in a.bulletin.bands.items()},
                "live": not a.bulletin.use_fixture,
            })
        return jsonify(out)

    @app.get("/api/bulletin")
    def bulletin():
        slug = request.args.get("aoi", "castle-peak")
        now = time.time()

        if slug in _cache and now - _cache[slug][0] < CACHE_TTL:
            return jsonify(_cache[slug][1])

        try:
            aoi = load_aoi(slug)
        except FileNotFoundError as e:
            return jsonify({"error": str(e)}), 404

        payload = get_adapter(aoi).get().to_dict()
        _cache[slug] = (now, payload)
        return jsonify(payload)

    @app.get("/api/aoi/<slug>/features")
    def aoi_features(slug: str):
        """Ski runs, lifts, and trails for one AOI, as GeoJSON.

        Replaces what the desktop client got from OpenSkiMap vector tiles.
        Cesium has no vector-tile pipeline, and whumpf is AOI-scoped anyway,
        so one bounding box of real features beats a world-wide tileset the
        renderer cannot read.

            /api/aoi/craigieburn/features
            /api/aoi/craigieburn/features?kinds=runs,lifts

        Always a FeatureCollection. An AOI with nothing mapped returns an
        empty one rather than a 404 -- absent features are a normal state,
        not a failure.
        """
        try:
            kinds = parse_kinds(request.args.get("kinds"))
        except ValueError as e:
            return jsonify({"error": str(e)}), 400

        try:
            aoi = load_aoi(slug)
        except FileNotFoundError as e:
            return jsonify({"error": str(e)}), 404

        now = time.time()
        cached = _features_cache.get(slug)
        if cached and now - cached[0] < FEATURES_CACHE_TTL:
            collection = cached[1]
        else:
            collection = get_feature_adapter(aoi).get()
            _features_cache[slug] = (now, collection)

        return jsonify(collection.to_dict(kinds))

    @app.get("/api/tiles/<slug>/<kind>/<int:z>/<int:x>/<path:name>")
    def local_tiles(slug: str, kind: str, z: int, x: int, name: str):
        """Serve locally-built XYZ tiles straight out of data/<slug>/.

        The production plan is static hosting on R2. This exists so you can
        see real terrain attributes before setting any of that up: run the
        pipeline, point VITE_ATTRIBUTE_TILES at this route, done. No object
        store, no credentials, no CDN.

        Not for production -- Flask is a poor tile server and this does no
        caching. It is for the machine you are developing on.
        """
        if kind not in ("attributes", "imagery"):
            abort(404)

        try:
            aoi = load_aoi(slug)
        except FileNotFoundError:
            abort(404)

        # gdal2tiles writes {z}/{x}/{y}.png with y in TMS order. The client
        # asks in XYZ order, so main.js flips it -- keep both ends aware of
        # that if you ever change the tiler.
        tile_dir = (aoi.data_dir / kind / str(z) / str(x)).resolve()
        root = aoi.data_dir.resolve()
        if not str(tile_dir).startswith(str(root)):
            abort(404)  # path traversal via ../ in the slug or coords
        if not tile_dir.is_dir():
            abort(404)

        response = send_from_directory(tile_dir, name)
        # Attribute tiles are regenerated by hand, so a long cache is wrong
        # during development -- you would keep seeing the previous build.
        response.headers["Cache-Control"] = "no-cache"
        return response

    @app.post("/api/route/analyze")
    def analyze_route():
        """Sample terrain along a polyline and flag segments matching the problem.

        Expected response:
            {
              "total_m": 3200,
              "flagged_m": 240,
              "segments": [{"start_idx": 12, "end_idx": 19, "length_m": 240}],
              "profile": [{"dist_m": 0, "elev_m": 2100, "slope": 18, "flagged": false}]
            }
        """
        body = request.get_json(silent=True) or {}
        coords = body.get("coordinates", [])
        if len(coords) < 2:
            return jsonify({"error": "need at least 2 coordinates"}), 400
        return jsonify({"error": "not implemented", "received_points": len(coords)}), 501

    return app


app = create_app()

if __name__ == "__main__":
    app.run(debug=True)
